import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header';
import localFont from 'next/font/local';
import { AuthProvider } from "@/context/AuthContext";
import ClientOnly from "@/components/ClientOnly";
import Sidebar from '@/components/Sidebar'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mythshire = localFont({
  src: '../assets/fonts/MythshireRegular.woff', // Path to your font file
  variable: '--mythshire', // Assign a CSS variable name
});

const simbiod = localFont({
  src: '../assets/fonts/Simbiod.ttf', // Path to your font file
  variable: '--simbiod', // Assign a CSS variable name
});

const fantasya = localFont({
  src: '../assets/fonts/Fantasya.otf', // Path to your font file
  variable: '--mythshire', // Assign a CSS variable name
});

const wizard = localFont({
  src: '../assets/fonts/Wizard.otf',
  variable: '--wizard',
})

const backover = localFont({
  src: '../assets/fonts/Backover-Regular.otf',
  variable: '--backoverregular',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ClientOnly>
        <Sidebar /> {/* <-- 2. ADD THE HEADER COMPONENT HERE */}
        </ClientOnly>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
